### ISSUE TITLE
Youtube app for samsung tvs?

### ISSUE THREAD

**Issue by arantesxyz** [contra/nodecast#24]
Is there a way to control the playback?

**Comment by yocontra** [comment]
Should work fine if they follow the specification

**Comment by arantesxyz** [comment]
Thanks, unfortunately it’s not possible to control the playback. Only start and stop, a limitation of DIAL.

im trying to figure it out how the youtube app on my phone communicates with the tv, and hoping it’s not through the cloud.

**Comment by yocontra** [comment]
@arantesxyz Maybe try using the `t` parameter - similar to how you can open a youtube url with `t=5` to skip to the 5 second point?

I would assume any in-app communication is done over the cloud and not through DIAL/local network comms.

**Comment by arantesxyz** [comment]
@yocontra Yes, that can help. But my objective was to have a channel on discord where people from my workplace can send youtube links and they would play on the tv. So I’d create a queue. And when the queue ends, youtube would take over with their auto play as always.

but yes, I think the communication between the yt app and the tv app is made by the cloud.

I’ll probably use airplay to stream the videos directly to the tv and control the playback and autoplay myself.

thank you for the help tho.
