### ISSUE TITLE
ChromeCast not launching apps

### ISSUE THREAD

**Issue by yocontra** [contra/nodecast#6]
Previously the lib was getting a 400 because some headers were wrong. This has been fixed but now we get a 201 and an empty body which usually means the app has been launched but nothing seems to happen. Trying to mess with this from a REST client always yields a 404.

This works:

```
curl http://192.168.1.120:8008/apps/YouTube -X POST -d 'v=j6N4vQ6m360'
```

**Comment by contra** [comment]
Will be fixed in next release
